apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwa-zbiorniki-regulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwa-zbiorniki-regulator
  template:
    metadata:
      labels:
        app: dwa-zbiorniki-regulator
    spec:
      containers:
        - name: regulator
          image: ghcr.io/jakubzasadni/dwa_zbiorniki-regulator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
