apiVersion: apps/v1
kind: Deployment
metadata:
  name: zbiornik-1rz-regulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zbiornik-1rz-regulator
  template:
    metadata:
      labels:
        app: zbiornik-1rz-regulator
    spec:
      containers:
        - name: regulator
          image: ghcr.io/jzasadni/zbiornik-1rz-regulator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
